"""
Forecast service — bridges the analytics pipeline with the FastAPI layer.

Priority:
  1. Real model: runs the analytics ETL + LightGBM (requires UK DATA.xlsx)
  2. Mock fallback: used when data files are not present (dev / demo without data)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PAU — the real model is already connected here.
To regenerate or refresh predictions:
    python -m analytics.run_pipeline            (from project root)
    python -m analytics.run_pipeline --promo 1  (simulate promo week)

The Impacto_Futbol feature has been disabled until proper per-match
importance weights are available. See analytics/forecaster.py for details.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional, List

# Make the project root importable so `analytics` can be found
# regardless of where uvicorn is launched from.
_PROJECT_ROOT = Path(__file__).resolve().parents[3]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from app.mocks import MOCK_FORECAST
from app.schemas import ForecastPoint


# ─── Revenue scale ───────────────────────────────────────────────────────────
# Venta Neta in UK DATA.xlsx is in thousands of euros.
# REVENUE_SCALE converts to actual euros; EUR_TO_GBP converts to £.
REVENUE_SCALE: float = 1_000.0
EUR_TO_GBP: float = 0.86   # approximate — update if needed

# ─── Feature flag ────────────────────────────────────────────────────────────
# True = use real data (CSV cache first, then live model as fallback)
# False = use centralised mocks (safe for demo without data files)
USE_REAL_DATA = True

# Pre-computed forecast CSV (generated by: python -m analytics.run_pipeline)
_CSV_PATH = _PROJECT_ROOT / "data" / "processed" / "forecast_weekly.csv"

# ─── Lazy model cache ────────────────────────────────────────────────────────
_model_cache: dict = {}

# In-memory CSV forecast cache — keyed by horizon. Filled on first call and
# reused for all subsequent requests so we never re-read the CSV from disk.
_csv_forecast_cache: dict = {}


def _load_from_csv(horizon: int) -> List[ForecastPoint]:
    """
    Serve forecast from the pre-computed CSV (fastest path, no model training).
    Uses the total_uk_retail segment. Falls back to individual segments summed
    if the total segment is not present.
    """
    import pandas as pd

    df = pd.read_csv(_CSV_PATH)

    # Prefer the aggregate segment; fall back to summing individual segments
    total = df[df["segmento"] == "total_uk_retail"].copy()
    if total.empty:
        individual = df[df["segmento"] != "total_uk_retail"]
        total = individual.groupby(["fecha", "tipo"], as_index=False).agg(
            venta_real=("venta_real", "sum"),
            prediccion=("prediccion", "sum"),
            limite_inferior_80=("limite_inferior_80", "sum"),
            limite_superior_80=("limite_superior_80", "sum"),
        )

    total = total.sort_values("fecha")

    # Revenue scale: venta_real is in Hl; convert using revenue-per-Hl ratio
    # derived from historical rows where both Hl and revenue are present.
    # As a safe default we use the EUR→GBP scaled Venta Neta from weekly_features.
    WEEKLY_FEATURES_PATH = _PROJECT_ROOT / "data" / "weekly_features.csv"
    try:
        wf = pd.read_csv(WEEKLY_FEATURES_PATH)
        total_hl = wf["Hl"].sum()
        total_rev = wf["Venta Neta"].sum() * 1_000 * EUR_TO_GBP
        rev_per_hl = total_rev / total_hl if total_hl > 0 else 228.0
    except Exception:
        rev_per_hl = 228.0  # £228/Hl fallback

    hist = total[total["tipo"] == "historico"]
    fut = total[total["tipo"] == "forecast"].head(horizon)

    # Monthly target: average of last 13 historical weeks × 4.33
    if not hist.empty:
        recent_rev = hist["venta_real"].tail(13) * rev_per_hl
        monthly_target = int(round(recent_rev.mean() * 4.33 / 10_000) * 10_000)
    else:
        monthly_target = 1_200_000

    weekly_target = int(monthly_target / 4.33)

    points: List[ForecastPoint] = []

    for _, row in hist.iterrows():
        hl = row.get("venta_real")
        actual_rev = int(round(float(hl) * rev_per_hl)) if hl and hl == hl else None
        points.append(ForecastPoint(
            date=_fmt_date(str(row["fecha"])),
            actual=actual_rev,
            target=weekly_target,
            forecast=actual_rev or 0,
            actionForecast=None,
            confidenceLow=None,
            confidenceHigh=None,
        ))

    for _, row in fut.iterrows():
        pred_hl = row.get("prediccion", 0) or 0
        low_hl = row.get("limite_inferior_80", pred_hl * 0.85) or pred_hl * 0.85
        high_hl = row.get("limite_superior_80", pred_hl * 1.15) or pred_hl * 1.15

        forecast_rev = int(round(float(pred_hl) * rev_per_hl))
        low_rev = int(round(float(low_hl) * rev_per_hl))
        high_rev = int(round(float(high_hl) * rev_per_hl))

        points.append(ForecastPoint(
            date=_fmt_date(str(row["fecha"])),
            actual=None,
            target=weekly_target,
            forecast=forecast_rev,
            actionForecast=int(forecast_rev * 1.15),
            confidenceLow=low_rev,
            confidenceHigh=high_rev,
        ))

    return points


def _build_real_forecast(horizon: int, channel: Optional[str]) -> List[ForecastPoint]:
    """
    Run ETL + LightGBM and return ForecastPoints in £.

    The analytics model predicts volume in Hl. We convert to £ using the
    average historical revenue-per-Hl ratio from the training data.
    """
    from analytics.data_prep import run_etl
    from analytics.forecaster import WeeklyVolumeForecaster
    from analytics.config import TARGET_VOLUME_COL, TARGET_REVENUE_COL

    cache_key = f"model_{horizon}_{channel}"
    if cache_key not in _model_cache:
        weekly = run_etl()

        # Revenue-per-Hl conversion ratio (£ / Hl)
        # Venta Neta is in thousands of EUR → multiply by scale and EUR→GBP
        total_hl = weekly[TARGET_VOLUME_COL].sum()
        total_rev = weekly[TARGET_REVENUE_COL].sum() * REVENUE_SCALE * EUR_TO_GBP
        rev_per_hl: float = total_rev / total_hl if total_hl > 0 else 1.0

        model = WeeklyVolumeForecaster(horizon=horizon)
        result = model.fit(weekly)

        # Monthly target: use the average of the last 3 months of actual revenue
        # as a baseline target, rounded to the nearest 10k
        recent_weekly_rev = (weekly[TARGET_REVENUE_COL].tail(13) * REVENUE_SCALE * EUR_TO_GBP)
        monthly_target_from_data = int(round(recent_weekly_rev.mean() * 4.33 / 10_000) * 10_000)

        _model_cache[cache_key] = {
            "result": result,
            "weekly": weekly,
            "rev_per_hl": rev_per_hl,
            "monthly_target": monthly_target_from_data,
        }

    cached = _model_cache[cache_key]
    result = cached["result"]
    weekly = cached["weekly"]
    rev_per_hl: float = cached["rev_per_hl"]
    monthly_target: int = cached["monthly_target"]

    weeks_in_month = 4.33
    weekly_target = int(monthly_target / weeks_in_month)

    points: List[ForecastPoint] = []

    # Historical rows
    for _, row in result.history.iterrows():
        actual_hl = row["venta_real_historica"]
        actual_rev = (
            int(round(actual_hl * rev_per_hl))
            if actual_hl is not None and actual_hl == actual_hl  # NaN check
            else None
        )
        points.append(
            ForecastPoint(
                date=_fmt_date(row["fecha"]),
                actual=actual_rev,
                target=weekly_target,
                forecast=actual_rev or 0,
                actionForecast=None,
                confidenceLow=None,
                confidenceHigh=None,
            )
        )

    # Future rows
    for _, row in result.future.iterrows():
        pred_hl = row["prediccion_futura"]
        low_hl = row["limite_inferior"]
        high_hl = row["limite_superior"]

        forecast_rev = int(round(pred_hl * rev_per_hl)) if pred_hl == pred_hl else 0
        low_rev = int(round(low_hl * rev_per_hl)) if low_hl == low_hl else None
        high_rev = int(round(high_hl * rev_per_hl)) if high_hl == high_hl else None

        # Action forecast: simulate 15% uplift with promo active
        action_rev = int(forecast_rev * 1.15)

        points.append(
            ForecastPoint(
                date=_fmt_date(row["fecha"]),
                actual=None,
                target=weekly_target,
                forecast=forecast_rev,
                actionForecast=action_rev,
                confidenceLow=low_rev,
                confidenceHigh=high_rev,
            )
        )

    return points


def _fmt_date(iso_date: str) -> str:
    """Convert '2026-05-04' → 'May 04' to match frontend format."""
    from datetime import datetime
    try:
        dt = datetime.strptime(iso_date, "%Y-%m-%d")
        return dt.strftime("%b %d")
    except ValueError:
        return iso_date


def predict_forecast(
    horizon: int = 6,
    channel: Optional[str] = None,
) -> List[ForecastPoint]:
    """
    Return the sales forecast time series.

    Args:
        horizon: number of weeks ahead to predict.
        channel: optional channel filter. Currently applies to the ETL
                 but the model predicts total UK volume. Channel-level
                 models can be added per segment when data volume allows.

    Returns:
        List of ForecastPoint with actual/forecast/target in £ and
        confidence bands. Falls back to mock data if real data is unavailable.
    """
    if not USE_REAL_DATA:
        return [ForecastPoint(**p) for p in MOCK_FORECAST]

    # ── Priority 1: in-memory CSV cache (instant on hot path) ────────────────
    if horizon in _csv_forecast_cache:
        return _csv_forecast_cache[horizon]

    # ── Priority 2: pre-computed CSV (fast, no training) ─────────────────────
    if _CSV_PATH.exists():
        try:
            result = _load_from_csv(horizon)
            _csv_forecast_cache[horizon] = result
            return result
        except Exception as exc:
            import logging
            logging.getLogger(__name__).warning(
                "CSV forecast load failed (%s), trying live model.", exc
            )

    # ── Priority 3: live LightGBM model (slow — only if CSV missing) ─────────
    try:
        return _build_real_forecast(horizon, channel)
    except FileNotFoundError:
        return [ForecastPoint(**p) for p in MOCK_FORECAST]
    except Exception as exc:
        import logging
        logging.getLogger(__name__).warning(
            "Live forecast failed (%s), falling back to mocks.", exc
        )
        return [ForecastPoint(**p) for p in MOCK_FORECAST]


def prewarm_cache(horizon: int = 13) -> None:
    """Load the forecast CSV into memory at app startup so the first
    HTTP request doesn't pay the disk-read latency."""
    if not USE_REAL_DATA or not _CSV_PATH.exists():
        return
    try:
        _csv_forecast_cache[horizon] = _load_from_csv(horizon)
    except Exception:
        pass
